version: "3.9"
services:
  sentiment:
    image: mcr.microsoft.com/azure-cognitive-services/textanalytics/sentiment:3.0-en
    ports:
    - 5000:5000
    environment:
      - Eula=accept
      - ApiKey=840377aac7454b31b09d4d03f9b95ffd
      - Billing=https://g5-language-service.cognitiveservices.azure.com/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  app:
    # image: ghcr.io/game-ai-project/g5-backend-service:latest
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      sentiment:
        condition: service_healthy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
