version: "3.9"
services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
